set -s escape-time 0

# set -s default-terminal tmux-256color
set -g default-terminal "screen-256color"
set -as terminal-overrides ",*:Tc"

source-file ~/.tmux-themepack/powerline/default/magenta.tmuxtheme

bind r source-file ~/.tmux.conf \; display 'tmux conf sourced bitch'

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Movement vim-like aww yeah baby
bind -n C-M-h select-pane -L
bind -n C-M-l select-pane -R
bind -n C-M-j select-pane -D
bind -n C-M-k select-pane -U

# Resize like a puta
bind -r H resize-pane -L 2
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2

bind -n C-Pageup   previous-window
bind -n C-Pagedown next-window

# Set new panes to open in current directory
bind c new-window -c "#{pane_current_path}"
bind - split-window -c "#{pane_current_path}"
bind _ split-window -h -c "#{pane_current_path}"
